#!/usr/bin/env python3
"""Build-time cache of the unchanged original-derived renderer; no hand drawn data."""
import ctypes, hashlib, json, subprocess
from pathlib import Path

def generate(app, out):
    lib=out/'logical-host.dylib'
    subprocess.run(['cc','-shared','-fPIC','-I'+str(app/'src'),str(app/'src/original/logical.c'),'-o',str(lib)],check=True)
    c=ctypes.CDLL(str(lib)); frame=(ctypes.c_ubyte*6144)()
    lines=['/* Generated by prepare_frames.py from original/logical.c. */']; records=[]
    for index,(fade,msg) in enumerate([(n,0) for n in range(0,33,2)]+[(0,1),(255,0)]):
        c.wizard_frame(frame,fade,msg); raw=bytes(frame); encoded=[]; i=0
        while i<len(raw):
            j=i+1
            while j<len(raw) and raw[j]==raw[i] and j-i<255:j+=1
            encoded.extend((j-i,raw[i]));i=j
        decoded=b''.join(bytes([v])*n for n,v in zip(encoded[::2],encoded[1::2]))
        assert decoded==raw
        lines.append('static const unsigned char cached_%d[]={%s};'%(index,','.join(map(str,encoded))))
        records.append(dict(fade=fade,messages=msg,sha256=hashlib.sha256(raw).hexdigest(),bytes=len(encoded)))
    lines.append('static const unsigned char * const cached_frames[]={'+','.join('cached_'+str(i) for i in range(19))+'};')
    (out/'frame-cache.h').write_text('\n'.join(lines)+'\n')
    (out/'frame-cache.json').write_text(json.dumps(records,indent=2)+'\n')
    return out/'frame-cache.h'
