#include <cmoc.h>
#include "logical.h"
#include "frame-cache.h"
/* Cache is generated by executing unchanged original/logical.c on the host.
 * It removes slow general 32-bit C vector arithmetic from timed playback.
 * A full logical 256x192 framebuffer is reconstructed before presentation. */
void playback_frame(unsigned char *frame,unsigned char fade,unsigned char messages)
{
    const unsigned char *p=cached_frames[messages?17:(fade==255?18:fade/2)];
    unsigned int left=FRAME_BYTES;
    while(left){unsigned char n=*p++,v=*p++;memset(frame,v,n);frame+=n;left-=n;}
}
